# Copyright (c) 2025, NVIDIA CORPORATION.

ignored:
  # warning: Using latest is prone to errors if the image will ever update
  #- DL3007
  # warning: Pin versions in apt get install.
  - DL3008
  # warning: Pin versions in pip.
  - DL3013
  # warning: Avoid use of cache directory with pip.
  - DL3042
