# Copyright (c) 2025, NVIDIA CORPORATION.
---
ci:
  autoupdate_schedule: 'monthly'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        args: ["--config", "pyproject.toml"]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        args: ["--severity=warning", "--external-sources"]
  - repo: https://github.com/rapidsai/pre-commit-hooks
    rev: v0.7.0
    hooks:
      - id: verify-copyright
        files: |
          (?x)
              [.](jq|py|sh|toml|yml|yaml)$|
              Dockerfile$
