ARG CUDA_VERSION=9.2
ARG CUDA_MAJORMINOR_VERSION=${CUDA_VERSION}
ARG LINUX_VERSION=ubuntu16.04
FROM nvidia/cuda:${CUDA_VERSION}-devel-${LINUX_VERSION}

ARG CUDA_MAJORMINOR_VERSION

insertfile args
insertfile env_ubuntu
insertfile updateos_ubuntu
insertfile setup_conda
insertfile copy_and_build_rapids

# Copy notebooks, leave git meta-data, EXPOSE ports, WORKDIR=/rapids/notebooks
insertfile finalize_image_devel


