#!/bin/bash

USAGE="
USAGE: $0
"

if (( $# > 0 )); then
    echo "${USAGE}"
    exit 1
fi

CONFIGFILE=$(dirname $0)/../config

#
# awk script processes config file line-by-line.
#
awk --assign debug=${DEBUG} '
    BEGIN {
       inRapidsSection = 0
    }
    /^# SECTION: RAPIDS.*$/ {
       inRapidsSection = 1
       next
    }      
    /^# SECTION: .*$/ {
       inRapidsSection = 0
       next
    }      
    /^[a-zA-Z0-9]+_REPO=.+$/ {
       if (inRapidsSection == 0) {
          next
       }
       split($0, fields, "=")
       var = fields[1]
       url = fields[2]
       split(var, fields, "_")
       repo = fields[1]
       split(url, fields, "/")
       last = fields[length(fields)]
       split(last, fields, ".")
       dir = fields[1]
       repourls[repo] = url
       repodirs[repo] = dir
       next
    }
    /^[a-zA-Z0-9]+_BRANCH=.+$/ {
       if (inRapidsSection == 0) {
          next
       }
       split($0, fields, "=")
       var = fields[1]
       branch = fields[2]
       split(var, fields, "_")
       repo = fields[1]
       repobranches[repo] = branch
       next
    }
    END {
       for (repo in repourls) {
          url = repourls[repo]
          dir = repodirs[repo]
          branch = repobranches[repo]
          printf("clone %s %s %s\n",url, dir, branch)
       }
    }
    ' ${CONFIGFILE}
