#!/bin/bash

USAGE="
USAGE: $0
"

if (( $# > 0 )); then
    echo "${USAGE}"
    exit 1
fi

CONFIGFILE=$(dirname $0)/../config

#
# awk script processes config file line-by-line.
# If line is "insertfile <file>", then cat the file to the generated output,
# If line is "runcommand <cmd> [<arg> ...]", then run the command with
# args and add the command output to the output,
# otherwise print the line as-is to the output.
#
awk --assign debug=${DEBUG} '
    BEGIN {
       inDependenciesSection = 0
    }
    /^# SECTION: DEPENDENCIES.*$/ {
       inDependenciesSection = 1
       next
    }      
    /^# SECTION: .*$/ {
       inDependenciesSection = 0
       next
    }      
    /^[^\ \t]+$/ {
       if (inDependenciesSection) {
          printf( "ARG %s\n", $0 )
       }
    }
    ' ${CONFIGFILE}
