name: Build and publish images workflow

on:
  workflow_call:
    inputs:
      repo:
        type: string
      branch:
        type: string
      date:
        type: string
      sha:
        type: string
      build_type:
        required: true
        type: string

      push:
        required: true
        type: boolean

defaults:
  run:
    shell: bash

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  discussions: none
  id-token: write
  issues: none
  packages: read
  pages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  compute-matrix:
    runs-on: ubuntu-latest
    outputs:
      MATRIX: ${{ steps.compute-matrix.outputs.MATRIX }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compute matrix
        id: compute-matrix
        run: ./ci/compute-matrix.sh
  docker-build-per-arch:
    needs: compute-matrix
    strategy:
      matrix: ${{ fromJSON(needs.compute-matrix.outputs.MATRIX) }}
    runs-on: ${{ fromJSON(matrix.runner_arch != 'arm64' && '"ubuntu-latest"' || '{"labels":["self-hosted", "linux", "arm64", "cpu4"]}') }}
    env:
      RAPIDS_BUILD_TYPE: ${{ inputs.build_type }}
    steps:
      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-duration-seconds: 43200 # 12h
      - name: Checkout
        uses: actions/checkout@v3
      - name: Standardize repository information
        uses: rapidsai/shared-action-workflows/rapids-github-info@branch-23.06
        with:
          repo: ${{ inputs.repo }}
          branch: ${{ inputs.branch }}
          date: ${{ inputs.date }}
          sha: ${{ inputs.sha }}
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders
      - name: Download and untar gha-tools
        run: |
          set -x
          sudo apt-get update -y && sudo apt-get install -y awscli git
          git clone https://github.com/sevagh/gha-tools -b feat/docker-s3 ./gha-tools
          chmod +x ./gha-tools/tools/*
          sudo cp ./gha-tools/tools/* /usr/bin/
      - name: Build and push intermediate images to s3
        run: ./ci/build_and_tag_images.sh
        env:
            CUDA_VER: ${{ matrix.CUDA_VER }}
            LINUX_VER: ${{ matrix.LINUX_VER }}
            PYTHON_VER: ${{ matrix.PYTHON_VER }}
            RAPIDS_VER: ${{ matrix.RAPIDS_VER }}
            DASK_SQL_VER: ${{ matrix.DASK_SQL_VER }}
  docker-assemble-push-multiarch:
    needs: [compute-matrix, docker-build-per-arch]
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
      RAPIDS_BUILD_TYPE: ${{ inputs.build_type }}
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-duration-seconds: 43200 # 12h
      - name: Checkout
        uses: actions/checkout@v3
      - name: Standardize repository information
        uses: rapidsai/shared-action-workflows/rapids-github-info@branch-23.06
        with:
          repo: ${{ inputs.repo }}
          branch: ${{ inputs.branch }}
          date: ${{ inputs.date }}
          sha: ${{ inputs.sha }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Download and untar gha-tools
        run: |
          set -x
          sudo apt-get update -y && sudo apt-get install -y awscli git
          git clone https://github.com/sevagh/gha-tools -b feat/docker-s3 ./gha-tools
          chmod +x ./gha-tools/tools/*
          sudo cp ./gha-tools/tools/* /usr/bin/
      - name: Assemble multiarch manifest from s3
        run: |
          set -x
          rapids-docker-multiarch-from-s3
