# Updates the DockerHub READMEs anytime a push to a release tag occurs.

name: Update DockerHub READMEs

on:
  push:
    tags:
      - v[0-9][0-9].[0-9][0-9].[0-9][0-9]
    paths:
      - dockerhub-readme.md
      - .github/workflows/dockerhub-readme.yml

jobs:
  readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo_name:
          - rapidsai
          - rapidsai-notebooks
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: DockerHub README >>> ${{ matrix.repo_name }}
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: rapidsai/${{ matrix.repo_name }}
          readme-filepath: dockerhub-readme.md
