# Updates nightly (but not stable) DockerHub READMEs anytime
# a push to `branch-**` occurs.

name: Update DockerHub READMEs

on:
  push:
    branches:
      - branch-**
    paths:
      - dockerhub-readme/generated-readmes/*nightly*.md
      - .github/workflows/dockerhub-readme-nightly.yml

jobs:
  readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo_name:
          - rapidsai-nightly
          - rapidsai-dev-nightly
          - rapidsai-core-nightly
          - rapidsai-core-dev-nightly
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: DockerHub README >>> ${{ matrix.repo_name }}
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: rapidsai/${{ matrix.repo_name }}
          readme-filepath: dockerhub-readme/generated-readmes/${{ matrix.repo_name }}.md
