# Copyright (c) 2023-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
name: ci

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Please keep pr-builder as the top job here
  pr-builder:
    needs:
      - changed-files
      - check-nightly-ci
      - docker
    permissions:
      checks: write
      pull-requests: write
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@main # zizmor: ignore[unpinned-uses]
    if: always()
    with:
      needs: ${{ toJSON(needs) }}
  changed-files:
    permissions:
      actions: read
      contents: read
      packages: read
      pull-requests: read
    uses: rapidsai/shared-workflows/.github/workflows/changed-files.yaml@main # zizmor: ignore[unpinned-uses]
    with:
      files_yaml: |
        build_images:
          - '**'
          - '!.github/CODEOWNERS'
          - '!.github/ISSUE_TEMPLATE/**'
          - '!.github/copy-pr-bot.yaml'
          - '!.github/ops-bot.yaml'
          - '!.github/release.yml'
          - '!.github/workflows/publish.yml'
          - '!.github/workflows/release-to-nvstaging.yml'
          - '!.github/workflows/trigger-breaking-change-alert.yaml'
          - '!.github/zizmor.yml'
          - '!.gitignore'
          - '!.pre-commit-config.yaml'
          - '!CONTRIBUTING.md'
          - '!LICENSE'
          - '!README.md'
          - '!SECURITY.md'
          - '!ci/release/update-version.sh'
          - '!context/scripts/README.md'
          - '!cuvs-bench/README.md'
          - '!dockerhub-readme.md'
          - '!pyproject.toml'
          - '!renovate.json'
          - '!tests/container-canary/README.md'
  check-nightly-ci:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Get PR Info
        id: get-pr-info
        uses: nv-gha-runners/get-pr-info@main # zizmor: ignore[unpinned-uses]
      - name: Check if nightly CI is passing
        uses: rapidsai/shared-actions/check_nightly_success/dispatch@main # zizmor: ignore[unpinned-uses]
        with:
          # default is 7 days, but this repo is downstream of all of RAPIDS so allow a bit longer window
          max-days-without-success: 14
          repo: ${{ github.repository }}
          target-branch: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).base.ref }}
          workflow-id: 'publish.yml'
  docker:
    needs: changed-files
    if: fromJSON(needs.changed-files.outputs.changed_file_groups).build_images
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: read
      pull-requests: read
    uses: $/.github/workflows/build-test-publish-images.yml
    with:
      build_type: pull-request
      run_tests: true
    secrets: inherit # zizmor: ignore[secrets-inherit]
